authors:
  gardener:
    name: Max Morev
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/45400275
    url: https://github.com/codemonstersteam
  huggybear:
    name: Maxim Morev
    description: Software Engineer
    avatar: https://avatars.githubusercontent.com/u/45400275
    url: https://github.com/max0l0gy